### ISSUE TITLE
Icon/Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [officialhord/EasyEncrypt#5]
Hi Sir @officialhord , I am a graphic designer and i want to contribute to your nice project by proposing an icon/logo design. I have created a design already and if you like and want to use it, I will be gladly sending you the files as a gift for free. Here's the design Sir.

Design Idea: You can see a message bubble and a key which represents encryption and decryption idea.
                      In the circle part of the key you will notice two letter "e" one is in reversed position that 
                      represents the initials for EasyEncrypt.

![post-01](https://user-images.githubusercontent.com/36028424/39905109-3d82b452-550e-11e8-9e8a-ddc6d80aa826.png)

I hope you like & will use it!

Best regards,
-Tobaloidee

**Comment by officialhord** [comment]
These are really awesome thanks.... Accepted will add them to the program

**Comment by Tobaloidee** [comment]
Hi Sir! Im so glad that you liked it and will use it..I will prepare the needed files and send it here asap.can i make a PR to update your readme or you will do it? Many thanks Sir!

**Comment by officialhord** [comment]
Thanks man

Sent from Mail for Windows 10

**Comment by Tobaloidee** [comment]
You are most welcome Sir!
